pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.minecraftforge.net/" }
        maven { url "https://maven.neoforged.net/releases/" }
        gradlePluginPortal()
    }
}

def enabledPlatforms = providers.gradleProperty("enabled_platforms").orElse("neoforge").get().split(",").collect { it.trim() }

include("common")
if (enabledPlatforms.contains("fabric")) {
    include("fabric")
}
if (enabledPlatforms.contains("neoforge")) {
    include("neoforge")
}